---
- name : installe multiple packege
  hosts: all
  become: true
  tasks:
  - name: install packeges
    yum:
     name: ['git', 'make', 'wget', 'telnet', 'tree', 'which', 'docker']
     state: installed
