---
- name: playbook when condition
  hosts: all
  become: true
  tasks:
  - name: install httpd packege
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd servcie
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  - name: install apache package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
