---
# tasks file for setup-apche-role
- name: install httpd packege
  yum:
    name: "{{ httpd_package_name }}"
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd servcie

- name: install apache package
  apt:
    name: "{{ apache2_package_name}}"
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache service

- name: copy index.html
  copy:
     src: /home/ansadmin/index.html
     dest: /var/www/html
     mode: 0666
